// Package main implements a tool to debug and visualize AI prompts generated by the pipeline.
// It uses pre-defined test scenarios to run through the entire prompt building and AI response cycle.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/BrightGir/game-ai-helper/assets"
	"github.com/BrightGir/game-ai-helper/internal/ai"
	"github.com/BrightGir/game-ai-helper/internal/ai/openrouter"
	"github.com/BrightGir/game-ai-helper/internal/dota"
	"github.com/BrightGir/game-ai-helper/internal/prompt"
	"github.com/BrightGir/game-ai-helper/internal/retriever"
	"github.com/BrightGir/game-ai-helper/internal/state"
	"github.com/joho/godotenv"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const (
	testDataDir   = "internal/prompt/testdata"          // Directory with scenario JSON files
	outputDir     = "cmd/rag/prompt-debug/debug_output" // Directory for debug output files
	Model         = "qwen/qwen-2.5-72b-instruct"        // Model to use for debugging
	MinSimilarity = 0.5                                 // Similarity threshold for RAG search during debug
)

// TestScenario represents a single test case with game state and user input.
type TestScenario struct {
	dota.GameState
	UserContext  string `json:"user_context"`
	UserQuestion string `json:"user_question"`
}

func main() {
	_ = godotenv.Load()

	apiKey := os.Getenv("PROMPT_DEBUG_API_KEY")
	if apiKey == "" {
		log.Fatal("Error: PROMPT_DEBUG_API_KEY not found.")
	}

	// Initialize AI client and RAG components
	aiClient := openrouter.NewClient(apiKey, Model, 30)
	bert, err := retriever.CreateEmbedFunction()
	if err != nil {
		log.Fatalf("Error initializing BERT %v", err)
	}

	searcher, err := retriever.CreateLocal(bert, MinSimilarity, assets.KnowledgeJSON)
	if err != nil {
		log.Fatalf("Error creating retriever %v", err)
	}

	// Setup the prompt pipeline
	pp := prompt.NewPipeline(aiClient, searcher)

	// Create a unique run ID for this debug session
	runID := time.Now().Format("15-04-05")
	currentOutDir := filepath.Join(outputDir, runID)
	os.MkdirAll(currentOutDir, 0755)

	log.Printf("Starting prompt debug. Results in: %s", currentOutDir)

	// Find all scenario files
	files, err := filepath.Glob(filepath.Join(testDataDir, "*.json"))
	if err != nil || len(files) == 0 {
		log.Fatalf("Files not found in %s: %v", testDataDir, err)
	}

	// Process each scenario
	for _, file := range files {
		processRealRun(aiClient, file, currentOutDir, pp)
	}
}

// processRealRun executes a single debug scenario and saves the result to a file.
func processRealRun(client ai.Client, filePath string, outDir string, pp *prompt.Pipeline) {
	baseName := filepath.Base(filePath)
	fmt.Printf("Handling: %s ... ", baseName)

	// Load scenario data
	data, _ := os.ReadFile(filePath)
	var scenario TestScenario
	_ = json.Unmarshal(data, &scenario)

	// Setup mock state and context
	st := state.NewStore()
	st.Update(&scenario.GameState)

	ctxProvider := &ContextProvider{
		Text: scenario.UserContext,
	}

	// Build the final prompt using the pipeline
	builder := prompt.NewBuilder(st, ctxProvider, pp)
	question := scenario.UserQuestion

	start := time.Now()
	finalPrompt, err := builder.Build(context.Background(), question)
	buildDuration := time.Since(start)

	if err != nil {
		fmt.Printf("FAIL (Build): %v\n", err)
		return
	}

	// Generate AI response based on the built prompt
	startAnswer := time.Now()
	aiAnswer, err := GenerateAnswer(context.Background(), client, finalPrompt)
	answerDuration := time.Since(startAnswer)

	if err != nil {
		fmt.Printf("FAIL (AI Answer): %v\n", err)
		return
	}

	fmt.Printf("OK (Build: %.2fs, AI: %.2fs)\n", buildDuration.Seconds(), answerDuration.Seconds())

	// Save debug information to a text file
	outFileName := strings.TrimSuffix(baseName, ".json") + "_result.txt"
	content := fmt.Sprintf(
		"FILE: %s\nQUESTION: %s\nGENERATION TIME: %.2fs\n"+
			"========================================\n"+
			"%s\n"+
			"========================================\n\n"+
			"[AI RESPONSE] (%.2fs)\n"+
			"%s\n",
		baseName, question, buildDuration.Seconds(), finalPrompt, answerDuration.Seconds(), aiAnswer,
	)

	os.WriteFile(filepath.Join(outDir, outFileName), []byte(content), 0644)
}

// GenerateAnswer sends the final prompt to the LLM.
func GenerateAnswer(ctx context.Context, client ai.Client, finalPrompt string) (string, error) {
	// Note: systemPrompt is passed as the second argument here
	answer, err := client.Ask(ctx, assets.BaseCoachSystemPrompt, finalPrompt)
	if err != nil {
		return "", err
	}
	return answer, nil
}

// ContextProvider is a mock provider for user context during debugging.
type ContextProvider struct {
	Text string
}

func (p *ContextProvider) GetContextText() string {
	return p.Text
}
